
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: storageos
    app.kubernetes.io/component: node-manager
  name: storageos:node-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: storageos:node-manager
subjects:
- kind: ServiceAccount
  name: storageos-node-manager
  namespace: node-manager-system
