apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: storageos-operator
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storageos-operator
  namespace: storageos
  labels:
    control-plane: storageos-operator
  annotations:
    kubectl.kubernetes.io/default-logs-container: manager
spec:
  selector:
    matchLabels:
      control-plane: storageos-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: storageos-operator
    spec:
      serviceAccountName: storageos-operator
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        envFrom:
          - configMapRef:
              name: storageos-related-images
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        image: controller:latest
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 5m
            memory: 80Mi
      terminationGracePeriodSeconds: 10
