
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: storageos
    app.kubernetes.io/component: api-manager
  name: storageos:api-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: storageos:api-manager
subjects:
- kind: ServiceAccount
  name: storageos-api-manager
  namespace: storageos
