
apiVersion: v1
kind: Service
metadata:
  labels:
    app: storageos
    app.kubernetes.io/component: api-manager
  name: storageos-api-manager-metrics
  namespace: storageos
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: storageos
    app.kubernetes.io/component: api-manager
  sessionAffinity: None
  type: ClusterIP
