apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: storageos:operator:node-manager
rules:
- apiGroups:
  - api.storageos.com
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.storageos.com
  resources:
  - volumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storageos.com
  resources:
  - storageosclusters
  verbs:
  - get
  - list
  - watch
