apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "storageos.com/v1",
          "kind": "StorageOSCluster",
          "metadata": {
            "name": "storageoscluster-sample"
          },
          "spec": {
            "kvBackend": {
              "address": "etcd-client:2379"
            },
            "secretRefName": "storageos-api",
            "storageClassName": "storageos"
          }
        }
      ]
    capabilities: Deep Insights
    categories: Storage
    containerImage: storageos/operator:v2.5.0
    createdAt: ""
    description: Cloud-native, persistent storage for containers.
    repository: https://github.com/storageos/operator
    support: StorageOS, Inc
  name: storageosoperator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: StorageOSCluster is the Schema for the storageosclusters API
      displayName: StorageOS Cluster
      kind: StorageOSCluster
      name: storageosclusters.storageos.com
      resources:
      - kind: Deployment
        name: storageos-api-manager
        version: apps/v1
      - kind: Deployment
        name: storageos-csi-helper
        version: apps/v1
      - kind: DaemonSet
        name: storageos-node
        version: apps/v1
      - kind: Deployment
        name: storageos-scheduler
        version: apps/v1
      specDescriptors:
      - description: Debug is to set debug mode of the cluster.
        displayName: Debug
        path: debug
      - description: Disable Telemetry.
        displayName: Disable Telemetry
        path: disableTelemetry
      - description: Images defines the various container images used in the cluster.
        displayName: Images
        path: images
      - description: KVBackend defines the key-value store backend used in the cluster.
        displayName: KVBackend
        path: kvBackend
      - description: NodeSelectorTerms is to set the placement of storageos pods using
          node affinity requiredDuringSchedulingIgnoredDuringExecution.
        displayName: Node Selector Terms
        path: nodeSelectorTerms
      - description: Resources is to set the resource requirements of the storageos
          containers.
        displayName: Resources
        path: resources
      - description: SecretRefName is the name of the secret object that contains
          all the sensitive cluster configurations.
        displayName: Secret Ref Name
        path: secretRefName
      - description: StorageClassName is the name of default StorageClass created
          for StorageOS volumes.
        displayName: Storage Class Name
        path: storageClassName
      - description: TLSEtcdSecretRefName is the name of the secret object that contains
          the etcd TLS certs. This secret is shared with etcd, therefore it's not
          part of the main storageos secret.
        displayName: TLSEtcd Secret Ref Name
        path: tlsEtcdSecretRefName
      - description: Tolerations is to set the placement of storageos pods using pod
          toleration.
        displayName: Tolerations
        path: tolerations
      statusDescriptors:
      - description: Conditions is a list of status of all the components of StorageOS.
        displayName: Conditions
        path: conditions
      - description: Members is the list of StorageOS nodes in the cluster.
        displayName: Members
        path: members
      - description: Phase is the phase of the StorageOS cluster.
        displayName: Phase
        path: phase
      - description: Ready is the ready status of the StorageOS control-plane pods.
        displayName: Ready
        path: ready
      version: v1
  description: |
    StorageOS is a cloud native, software-defined storage platform that
    transforms commodity server or cloud based disk capacity into
    enterprise-class persistent storage for containers. StorageOS volumes
    offer high throughput, low latency and consistent performance, and
    are therefore ideal for deploying databases, message queues, and
    other mission-critical stateful solutions. StorageOS Project edition
    also offers ReadWriteMany volumes that are concurrently accessible
    by multiple applications.

    The StorageOS Operator installs and manages StorageOS within a cluster.
    Cluster nodes may contribute local or attached disk-based storage into a
    distributed pool, which is then available to all cluster members via a
    global namespace.

    Volumes are available across the cluster so if a container gets moved to
    another node it has immediate access to re-attach its data.

    StorageOS is extremely lightweight - minimum requirements are a
    reserved CPU core and 2GB of free memory. There are minimal external
    dependencies, and no custom kernel modules.

    After StorageOS is installed, please register for a free Developer
    license to enable 5TiB of capacity and HA with synchronous
    replication by following the instructions
    [here](https://docs.storageos.com/docs/operations/licensing). For
    additional capacity, features and support plans contact
    sales@storageos.com.

    ## Highlighted Features

    * **High Availability** - synchronous replication insulates you from node failure.

    * **Delta Sync** - replicas out of sync due to transient failures only transfer changed blocks.

    * **Multiple AccessModes** - dynamically provision ReadWriteOnce or ReadWriteMany volumes.

    * **Rapid Failover** - quickly detects node failure and automates recovery actions without administrator intervention.

    * **Data Encryption** - both in transit and at rest.

    * **Scalability** - disaggregated consensus means no single scheduling point of failure.

    * **Thin provisioning** - Only consume the space you need in a storage pool.

    * **Data reduction** - transparent inline data compression to reduce the amount of storage used in a backing store as well as reducing the network bandwidth requirements for replication.

    * **Flexible configuration** - all features can be enabled per volume, using PVC and StorageClass labels.

    * **Multi-tenancy** - fully supports standard Namespace and RBAC methods.

    * **Observability & instrumentation** - log streams for observability and Prometheus support for instrumentation.

    * **Deployment flexibility** - scale up or scale out storage based on application requirements. Works with any infrastructure – on-premises, VM, bare metal or cloud.

    ## Prerequisites

    [StorageOS Prerequisites Docs](https://docs.storageos.com/docs/prerequisites)

    ## Required Parameters

    * `secretRefName` - the name of a secret that contains keys for the
    credentials
    ([documentation](https://docs.storageos.com/docs/reference/cluster-operator/examples))
    * `kvBackend.address` - address of the etcd cluster
    ([documentation](https://docs.storageos.com/docs/prerequisites/etcd/))

    ## About StorageOS

    StorageOS is a software-defined cloud native storage platform
    delivering persistent storage for Kubernetes. StorageOS is built from
    the ground-up with no legacy restrictions to give enterprises working
    with cloud native workloads a scalable storage platform with no
    compromise on performance, availability or security. For additional
    information, visit [www.storageos.com](www.storageos.com).
  displayName: StorageOS
  icon:
  - base64data: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAxOS4wLjAsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0iTGF5ZXJfMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgeD0iMHB4IiB5PSIwcHgiDQoJIHZpZXdCb3g9Ii05MCAyODQuNyA0MzAgNDMwIiBlbmFibGUtYmFja2dyb3VuZD0ibmV3IC05MCAyODQuNyA0MzAgNDMwIiB4bWw6c3BhY2U9InByZXNlcnZlIj4NCjxnPg0KCTxwYXRoIGZpbGw9IiM0RjUyNjMiIGQ9Ik0yNzguNSw0MjAuOWgtNzQuMWwtNS42LTkuN2wxMy42LTIzLjZsLTE4LjEtMzEuM0gxODBsMjcuNS00Ny43YzMtNS4xLDEuMi0xMS43LTMuOS0xNC42DQoJCWMtNS4xLTMtMTEuNy0xLjItMTQuNiwzLjlsLTM0LDU4LjhIOTMuMmwtMzQtNTguOGMtMi45LTUuMS05LjUtNi45LTE0LjYtMy45cy02LjksOS41LTMuOSwxNC42bDI3LjUsNDcuN0g1My45bC0xOC4xLDMxLjMNCgkJbDEzLjYsMjMuNmwtNS42LDkuOGgtNzQuMmwtNDMuMyw3NC45bDQzLjMsNzQuOWg3NC4xbDM0LDU4LjlMNzksNjI5bC0xLjIsMC44bDQ2LjQsNzcuMmw0Ni4yLTc3LjNsMCwwbDM0LTU4LjloNzQuMWw0My4zLTc0LjkNCgkJTDI3OC41LDQyMC45eiBNNTUuNSw0MDAuNWwtNy40LTEyLjhMNjAsMzY3aDE0LjNsMC4zLDAuNUw1NS41LDQwMC41eiBNMTczLjQsMzY3LjVsMC4zLTAuNUgxODhsMTEuOSwyMC42bC03LjQsMTIuOUwxNzMuNCwzNjcuNXoiDQoJCS8+DQoJPHBvbHlnb24gZmlsbD0iI0ZGRkZGRiIgcG9pbnRzPSI0My43LDQ0Mi4zIDQyLjgsNDQyLjMgLTE4LjEsNDQyLjMgLTQ4LjksNDk1LjggLTE4LjEsNTQ5LjMgNDMsNTQ5LjMgNDMuNyw1NDkuMyA3NC42LDQ5NS45IAkiLz4NCgk8cG9seWdvbiBmaWxsPSIjRkZGRkZGIiBwb2ludHM9IjI2Ni4xLDQ0Mi4zIDIwNC4zLDQ0Mi4zIDIwNC4zLDQ0Mi41IDE3My40LDQ5NS44IDIwNC4zLDU0OS4zIDIwNC40LDU0OS4zIDI2Ni4xLDU0OS4zIDI5Nyw0OTUuOCAJDQoJCSIvPg0KCTxwb2x5Z29uIGZpbGw9IiM2MUMyMDIiIHBvaW50cz0iMTU0LjksMzc4LjIgOTMuMSwzNzguMiA5My4xLDM3OC4zIDYyLjMsNDMxLjcgOTMuMSw0ODUuMiA5My4yLDQ4NS4yIDE1NC45LDQ4NS4yIDE4NS44LDQzMS43IAkiLz4NCgk8cG9seWdvbiBmaWxsPSIjNjFDMjAyIiBwb2ludHM9IjE1Mi4xLDYxOC40IDE1Mi4xLDYxOC40IDEyNCw2NjUuMiA5Ni4yLDYxOC45IDk2LjIsNjE4LjkgNjIuMiw1NjAuMSA4OC4zLDUxNC45IDkzLjEsNTA2LjYgDQoJCTE1NC45LDUwNi42IDE4NS44LDU2MC4xIAkiLz4NCjwvZz4NCjxyZWN0IHg9Ii0xMDUiIHk9IjI3MC43IiBmaWxsPSJub25lIiB3aWR0aD0iNDU4IiBoZWlnaHQ9IjQ1OCIvPg0KPC9zdmc+DQo=
    mediatype: image/svg+xml
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - storageos
  - storage
  - persistent storage
  - open source
  labels:
    operated-by: storageosoperator
  links:
  - name: Documentation
    url: https://docs.storageos.com
  - name: StorageOS Operator Source Code
    url: https://github.com/storageos/operator
  maintainers:
  - email: support@storageos.com
    name: StorageOS, Inc
  maturity: stable
  minKubeVersion: 1.18.0
  provider:
    name: StorageOS, Inc
    url: https://storageos.com
  selector:
    matchLabels:
      operated-by: storageosoperator
  version: 0.0.0
