commonLabels:
  app: storageos
  app.kubernetes.io/component: scheduler

resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- serviceaccount.yaml

configMapGenerator:
- files:
  - config.yaml
  name: storageos-scheduler

images:
  - name: kube-scheduler
    newName: k8s.gcr.io/kube-scheduler
    newTag: v1.18.0
