apiVersion: kuttl.dev/v1beta1
kind: TestSuite
testDirs:
- ./e2e/tests/deployment/stable
kindConfig: e2e/kind/kind-config-1.22.yaml
startKIND: true
kindNodeCache: true
kindContainers:
  - storageos/operator:test
timeout: 800
