
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: storageos
    app.kubernetes.io/component: api-manager
  name: storageos:key-management
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: storageos:key-management
subjects:
- kind: ServiceAccount
  name: storageos-api-manager
  namespace: storageos
- kind: ServiceAccount
  name: storageos-node
  namespace: storageos
