
apiVersion: v1
kind: Service
metadata:
  labels:
    app: storageos
    app.kubernetes.io/component: api-manager
  name: storageos-webhook
  namespace: storageos
spec:
  ports:
  - name: webhook
    port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app: storageos
    app.kubernetes.io/component: api-manager
  sessionAffinity: None
  type: ClusterIP
