apiVersion: apps/v1
kind: Deployment
metadata:
  name: storageos-csi-helper
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
      - args:
        - --v=5
        - --csi-address=$(ADDRESS)
        - --extra-create-metadata
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        image: csi-provisioner
        imagePullPolicy: IfNotPresent
        name: provisioner
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 5m
            memory: 30Mi
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
      - args:
        - --v=5
        - --csi-address=$(ADDRESS)
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        image: csi-attacher
        imagePullPolicy: IfNotPresent
        name: attacher
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 1m
            memory: 30Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
      - args:
        - --v=5
        - --csi-address=$(ADDRESS)
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        image: csi-resizer
        imagePullPolicy: IfNotPresent
        name: resizer
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 1m
            memory: 30Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      serviceAccountName: storageos-csi-helper
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: node.kubernetes.io/disk-pressure
        operator: Exists
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 30
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 30
      volumes:
      - hostPath:
          path: /var/lib/kubelet/plugins_registry/storageos
          type: DirectoryOrCreate
        name: plugin-dir
