name: Publish develop image

on:
  push:
    branches:
      - main

env:
  OPERATOR_IMAGE: storageos/operator:develop
  MANIFESTS_IMAGE: storageos/operator-manifests:develop

jobs:
  publish-image:
    runs-on: ubuntu-latest
    name: Publish container image
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_PASSWORD }}
      - name: Build container image
        run: make operator-image
      - name: Push container image
        run: make operator-image-push
  publish-manifests-image:
    runs-on: ubuntu-latest
    name: Publish manifests container image
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_PASSWORD }}
      - name: Run manifests image build
        run: make manifests-image
      - name: Push manifests container image
        run: docker push ${{ env.MANIFESTS_IMAGE }}
