name: Publish release image

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-image:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Publish container image
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Set image tag env var
        # Refer https://stackoverflow.com/a/58178121 for git tag extraction.
        run: echo "OPERATOR_IMAGE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set image env vars
        run: |
          echo "OPERATOR_IMAGE=storageos/operator:${{ env.OPERATOR_IMAGE_TAG }}" >> $GITHUB_ENV
          echo "RH_OPERATOR_IMAGE=scan.connect.redhat.com/${{ secrets.OSPID }}/cluster-operator2:${{ env.OPERATOR_IMAGE_TAG }}" >> $GITHUB_ENV
      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_PASSWORD }}
      - name: Build container image
        run: make operator-image
      - name: Push container image to dockerhub
        run: make operator-image-push
      - name: Login to redhat container registry
        uses: docker/login-action@v1
        with:
          registry: scan.connect.redhat.com
          username: ${{ secrets.RH_USERNAME }}
          password: ${{ secrets.RH_TOKEN }}
      - name: Push container image to redhat container registry
        run: |
          docker tag ${{ env.OPERATOR_IMAGE }} ${{ env.RH_OPERATOR_IMAGE }}
          make operator-image-push OPERATOR_IMAGE=${{ env.RH_OPERATOR_IMAGE }}
  publish-manifests-image:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Publish manifests container image
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_PASSWORD }}
      - name: Set image tag env var
        # Refer https://stackoverflow.com/a/58178121 for git tag extraction.
        run: |
          echo "OPERATOR_IMAGE=storageos/operator:${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "MANIFESTS_IMAGE=storageos/operator-manifests:${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Run manifests image build
        run: make manifests-image
      - name: Push manifests container image
        run: docker push ${{ env.MANIFESTS_IMAGE }}
